// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oddwsnuzajldagqoxyfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZHdzbnV6YWpsZGFncW94eWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTcyNDIsImV4cCI6MjA2NDUzMzI0Mn0.uBq8BFBTKlKtaher6po8rqfjgqaYrM8Afv6ZK3tDAjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);